apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: caesar-tls
spec:
  secretName: caesar-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "caesar.staging.mercury.local"
