apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 1h
  releaseName: cloudnative-pg
  targetNamespace: cnpg-system
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.22.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
  values:
    monitoring:
      podMonitorEnabled: true
