apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-plugin-barman-cloud
  namespace: cnpg-system
spec:
  interval: 1h
  chart:
    spec:
      chart: plugin-barman-cloud
      version: "0.3.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
