apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: julius-db
  namespace: julius
spec:
  instances: 2

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: julius-db-credentials

  storage:
    size: 5Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: julius-objectstore
