apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana-operator
      version: "v5.15.1"
      sourceRef:
        kind: HelmRepository
        name: grafana-operator
        namespace: flux-system
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
