apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 1h
  releaseName: grafana-operator
  targetNamespace: monitoring
  chart:
    spec:
      chart: grafana-operator
      version: "v5.15.1"
      sourceRef:
        kind: HelmRepository
        name: grafana-operator
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
